// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

using System.Collections.Immutable;
using System.Linq;
using System.Text;
using CommunityToolkit.Mvvm.SourceGenerators.Extensions;
using CommunityToolkit.Mvvm.SourceGenerators.Helpers;
using CommunityToolkit.Mvvm.SourceGenerators.Messaging.Models;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace CommunityToolkit.Mvvm.SourceGenerators;

/// <inheritdoc/>
partial class IMessengerRegisterAllGenerator
{
    /// <summary>
    /// A container for all the logic for <see cref="IMessengerRegisterAllGenerator"/>.
    /// </summary>
    private static class Execute
    {
        /// <summary>
        /// Gets the <c>IRecipient&lt;TMessage&gt;</c> interfaces from <paramref name="typeSymbol"/>, if any.
        /// </summary>
        /// <param name="typeSymbol">The input <see cref="INamedTypeSymbol"/> instance to inspect.</param>
        /// <returns>An array of interface type symbols.</returns>
        public static ImmutableArray<INamedTypeSymbol> GetInterfaces(INamedTypeSymbol typeSymbol)
        {
            using ImmutableArrayBuilder<INamedTypeSymbol> iRecipientInterfaces = ImmutableArrayBuilder<INamedTypeSymbol>.Rent();

            foreach (INamedTypeSymbol interfaceSymbol in typeSymbol.AllInterfaces)
            {
                if (interfaceSymbol.HasFullyQualifiedMetadataName("CommunityToolkit.Mvvm.Messaging.IRecipient`1"))
                {
                    iRecipientInterfaces.Add(interfaceSymbol);
                }
            }

            return iRecipientInterfaces.ToImmutable();
        }

        /// <summary>
        /// Gets the <see cref="RecipientInfo"/> instance from the given info.
        /// </summary>
        /// <param name="typeSymbol">The type symbol for the target type being inspected.</param>
        /// <param name="interfaceSymbols">The input array of interface type symbols being handled.</param>
        /// <returns>A <see cref="RecipientInfo"/> instance for the current type being inspected.</returns>
        public static RecipientInfo GetInfo(INamedTypeSymbol typeSymbol, ImmutableArray<INamedTypeSymbol> interfaceSymbols)
        {
            using ImmutableArrayBuilder<string> names = ImmutableArrayBuilder<string>.Rent();

            foreach (INamedTypeSymbol interfaceSymbol in interfaceSymbols)
            {
                names.Add(interfaceSymbol.TypeArguments[0].GetFullyQualifiedName());
            }

            return new(
                typeSymbol.GetFullyQualifiedMetadataName(),
                typeSymbol.GetFullyQualifiedName(),
                names.ToImmutable());
        }

        /// <summary>
        /// Gets the head source text for the header file.
        /// </summary>
        /// <param name="isDynamicallyAccessedMembersAttributeAvailable">Indicates whether <c>[DynamicallyAccessedMembers]</c> should be generated.</param>
        /// <returns>The generated source text for the header file.</returns>
        public static SourceText GetSyntax(bool isDynamicallyAccessedMembersAttributeAvailable)
        {
            StringBuilder sb = new StringBuilder();
            
            // Generate file header
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#pragma warning disable");
            sb.AppendLine();
            
            // Generate namespace
            sb.AppendLine("namespace CommunityToolkit.Mvvm.Messaging.__Internals");
            sb.AppendLine("{");
            
            // Generate class with documentation and attributes
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// A helper type with generated registration stubs for types implementing <see cref=\"global::CommunityToolkit.Mvvm.Messaging.IRecipient{T}\"/>.");
            sb.AppendLine("    /// </summary>");
            
            // Add GeneratedCode attribute
            string generatorName = typeof(IMessengerRegisterAllGenerator).FullName;
            string generatorVersion = typeof(IMessengerRegisterAllGenerator).Assembly.GetName().Version.ToString();
            sb.AppendLine($"    [global::System.CodeDom.Compiler.GeneratedCode(\"{generatorName}\", \"{generatorVersion}\")]");
            sb.AppendLine("    [global::System.Diagnostics.DebuggerNonUserCode]");
            sb.AppendLine("    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]");
            sb.AppendLine("    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
            sb.AppendLine("    [global::System.Obsolete(\"This type is not intended to be used directly by user code\")]");
            
            if (isDynamicallyAccessedMembersAttributeAvailable)
            {
                sb.AppendLine("    [global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMembersAttribute(global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicMethods)]");
            }
            
            sb.AppendLine("    internal static partial class __IMessengerExtensions");
            sb.AppendLine("    {");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            
            return SourceText.From(sb.ToString(), Encoding.UTF8);
        }

        /// <summary>
        /// Gets the source text for the input recipient.
        /// </summary>
        /// <param name="recipientInfo">The input <see cref="RecipientInfo"/> instance to process.</param>
        /// <returns>The generated source text for <paramref name="recipientInfo"/>.</returns>
        public static SourceText GetSyntax(RecipientInfo recipientInfo)
        {
            StringBuilder sb = new StringBuilder();
            
            // Generate file header
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#pragma warning disable");
            sb.AppendLine();
            
            // Generate namespace
            sb.AppendLine("namespace CommunityToolkit.Mvvm.Messaging.__Internals");
            sb.AppendLine("{");
            
            // Generate partial class
            sb.AppendLine("    /// <inheritdoc/>");
            sb.AppendLine("    partial class __IMessengerExtensions");
            sb.AppendLine("    {");
            
            // Generate the default channel method (without tokens)
            GenerateDefaultChannelMethod(sb, recipientInfo);
            
            sb.AppendLine();
            
            // Generate the custom channel method (with tokens)
            GenerateCustomChannelMethod(sb, recipientInfo);
            
            sb.AppendLine("    }");
            sb.AppendLine("}");
            
            return SourceText.From(sb.ToString(), Encoding.UTF8);
        }

        /// <summary>
        /// Generates the default channel registration method (without tokens).
        /// </summary>
        /// <param name="sb">The StringBuilder to append to.</param>
        /// <param name="recipientInfo">The recipient info.</param>
        private static void GenerateDefaultChannelMethod(StringBuilder sb, RecipientInfo recipientInfo)
        {
            // Generate method documentation and attributes
            sb.AppendLine("        /// <summary>");
            sb.AppendLine($"        /// Creates a message registration stub for <see cref=\"{recipientInfo.TypeName}\"/> objects.");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        /// <param name=\"_\">Dummy parameter, only used to disambiguate the method signature.</param>");
            sb.AppendLine($"        /// <returns>A message registration stub for <see cref=\"{recipientInfo.TypeName}\"/> objects.</returns>");
            sb.AppendLine("        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
            sb.AppendLine("        [global::System.Obsolete(\"This method is not intended to be called directly by user code\")]");
            
            // Generate method signature
            sb.AppendLine($"        public static global::System.Action<global::CommunityToolkit.Mvvm.Messaging.IMessenger, object> CreateAllMessagesRegistrator({recipientInfo.TypeName} _)");
            sb.AppendLine("        {");
            
            // Generate local function
            sb.AppendLine("            static void RegisterAll(global::CommunityToolkit.Mvvm.Messaging.IMessenger messenger, object obj)");
            sb.AppendLine("            {");
            sb.AppendLine($"                var recipient = ({recipientInfo.TypeName})obj;");
            
            // Generate registration statements
            foreach (string messageType in recipientInfo.MessageTypes)
            sb.AppendLine($"                messenger.Register<{messageType}>(recipient);");
            
            sb.AppendLine("            }");
            sb.AppendLine();
            sb.AppendLine("            return RegisterAll;");
            sb.AppendLine("        }");
        }

        /// <summary>
        /// Generates the custom channel registration method (with tokens).
        /// </summary>
        /// <param name="sb">The StringBuilder to append to.</param>
        /// <param name="recipientInfo">The recipient info.</param>
        private static void GenerateCustomChannelMethod(StringBuilder sb, RecipientInfo recipientInfo)
        {
            // Generate method documentation and attributes
            sb.AppendLine("        /// <summary>");
            sb.AppendLine($"        /// Creates a message registration stub for <see cref=\"{recipientInfo.TypeName}\"/> objects.");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        /// <typeparam name=\"TToken\">The type of tokens that will be used to register messages.</typeparam>");
            sb.AppendLine("        /// <param name=\"_\">Dummy parameter, only used to disambiguate the method signature.</param>");
            sb.AppendLine($"        /// <returns>A message registration stub for <see cref=\"{recipientInfo.TypeName}\"/> objects.</returns>");
            sb.AppendLine("        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
            sb.AppendLine("        [global::System.Obsolete(\"This method is not intended to be called directly by user code\")]");
            
            // Generate method signature with generic constraint
            sb.AppendLine($"        public static global::System.Action<global::CommunityToolkit.Mvvm.Messaging.IMessenger, object, TToken> CreateAllMessagesRegistratorWithToken<TToken>({recipientInfo.TypeName} _)");
            sb.AppendLine("            where TToken : global::System.IEquatable<TToken>");
            sb.AppendLine("        {");
            
            // Generate local function
            sb.AppendLine("            static void RegisterAll(global::CommunityToolkit.Mvvm.Messaging.IMessenger messenger, object obj, TToken token)");
            sb.AppendLine("            {");
            sb.AppendLine($"                var recipient = ({recipientInfo.TypeName})obj;");
            
            // Generate registration statements with tokens
            foreach (string messageType in recipientInfo.MessageTypes)
            sb.AppendLine($"                messenger.Register<{messageType}, TToken>(recipient, token);");
            
            sb.AppendLine("            }");
            sb.AppendLine();
            sb.AppendLine("            return RegisterAll;");
            sb.AppendLine("        }");
        }
    }
}
